#!/usr/bin/env python3
"""Run actual PhoenixNavigator mesh builders on macOS without building the app.

Usage: python3 Tools/RenderHarness/run_navigator_geometry_probe.py
Only platform color/material stubs and access control differ from production. SceneKit
vertices, indices, normals, and UVs are generated by the extracted Swift source.
"""
from pathlib import Path
import re
import subprocess
import tempfile


ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "Landfall/Views/Dress/PhoenixNavigator.swift"
PROBE = Path(__file__).with_name("NavigatorGeometryProbe.swift")


def block(source, start):
    """Read one Swift declaration, respecting quoted strings and comments."""
    brace = source.index("{", start)
    depth, cursor = 1, brace + 1
    while depth:
        if source.startswith("//", cursor):
            cursor = source.find("\n", cursor)
            if cursor < 0:
                raise ValueError("Unclosed declaration")
        elif source.startswith("/*", cursor):
            end = source.find("*/", cursor + 2)
            if end < 0:
                raise ValueError("Unclosed comment")
            cursor = end + 2
        elif source.startswith('"""', cursor):
            end = source.find('"""', cursor + 3)
            if end < 0:
                raise ValueError("Unclosed multiline string")
            cursor = end + 3
        elif source[cursor] == '"':
            cursor += 1
            while source[cursor] != '"':
                cursor += 2 if source[cursor] == "\\" else 1
            cursor += 1
        else:
            depth += (source[cursor] == "{") - (source[cursor] == "}")
            cursor += 1
    return source[start:cursor]


def main():
    source = SOURCE.read_text()
    methods = {}
    for match in re.finditer(r"^    (?:private )?static func (\w+)\b", source, re.MULTILINE):
        methods[match[1]] = block(source, match.start())
    requested = {"lathe", "openLathe", "makeHoodGeometry"}
    selected = set()
    while requested - selected:
        name = sorted(requested - selected)[0]
        if name not in methods:
            raise ValueError(f"Production builder missing: {name}")
        selected.add(name)
        body = methods[name]
        requested.update(candidate for candidate in methods if re.search(rf"\b{candidate}\s*\(", body))
    helpers = []
    for name in ("v3add", "v3sub", "v3cross", "v3norm"):
        match = re.search(rf"^private func {name}\b", source, re.MULTILINE)
        helpers.append(block(source, match.start()))
    # UIKit is unavailable on macOS. Geometry constructors and their production
    # math remain unchanged; SCNVector3 storage is decoded as Float or Double.
    platform = '''import Foundation
import AppKit
import SceneKit
typealias UIColor = NSColor
extension NSColor {
    convenience init(rgb: UInt32) {
        self.init(srgbRed: CGFloat((rgb >> 16) & 255) / 255,
                  green: CGFloat((rgb >> 8) & 255) / 255,
                  blue: CGFloat(rgb & 255) / 255, alpha: 1)
    }
}
struct NavigatorPalette {
    let robe = NSColor.gray
    let trim = NSColor.darkGray
    let deep = NSColor.black
}
// This is a geometry probe; UIKit texture generation is verified in Simulator.
enum NavigatorSurface {
    static func cloth(_ color: NSColor, roughness: CGFloat, doubleSided: Bool = false) -> SCNMaterial {
        let material = SCNMaterial()
        material.diffuse.contents = color
        material.roughness.contents = roughness
        material.isDoubleSided = doubleSided
        return material
    }
}
'''
    body = "\n\n".join(methods[name].replace("private static", "static") for name in sorted(selected))
    generated = platform + "\n".join(helpers) + "\nenum NavigatorGeometryProbeSubject {\n"
    generated += 'static let robeMaterialName = "LF_NavRobe"\n'
    generated += body + "\n}\n"
    with tempfile.TemporaryDirectory(prefix="navigator-geometry-") as directory:
        temporary = Path(directory)
        subject = temporary / "NavigatorGeometryProbeSubject.swift"
        subject.write_text(generated)
        executable = temporary / "probe"
        subprocess.run(["xcrun", "swiftc", "-parse-as-library", str(subject), str(PROBE), "-o", str(executable)], check=True)
        subprocess.run([str(executable)], check=True)


if __name__ == "__main__":
    main()
